services:
  app:
    build: .
    container_name: panorama_grani
    restart: unless-stopped
    env_file: .env
    ports:
      - "127.0.0.1:8001:8000"
    volumes:
      - app_data:/app/data
      - ./parser/json:/app/parser/json
      - ./esoft_front/static/img:/app/esoft_front/static/img
    environment:
      - DATABASE_URL=sqlite:///./data/users.db

  presenton:
    image: ghcr.io/presenton/presenton:latest
    container_name: presenton
    restart: unless-stopped
    ports:
      - "0.0.0.0:5001:80"
    volumes:
      - ./prod/presenton/app_data/exports:/app_data/exports

volumes:
  app_data:

